exec = require('child_process').exec
fs = require('fs')

task 'watch', 'Watch and compile', ->
  exec('coffee -cwo lib src').stdout.on 'data', (data) ->
    process.stdout.write(data)

task 'build', 'compile', ->
  exec('coffee -co lib src').stdout.on 'data', (data) ->
    process.stdout.write(data)