// Generated by CoffeeScript 1.9.2
(function() {
  var app, credentials, express, nodemailer, parser, transporter;

  nodemailer = require('nodemailer');

  credentials = require('./credentials');

  express = require('express');

  parser = require('body-parser');

  transporter = nodemailer.createTransport({
    host: credentials.host,
    secure: false,
    port: 25,
    auth: {
      user: credentials.email,
      pass: credentials.pass
    },
    tls: {
      rejectUnauthorized: false
    }
  });

  app = express();

  app.use(function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
    next();
  });

  app.use(parser.urlencoded({
    extended: true
  }));

  app.use(parser.json());

  app.post('/mailer', function(req, res) {
    var code, data, message;
    data = req.body.mail;
    if (typeof data.name === 'string' && typeof data.email === 'string' && typeof data.message === 'string') {
      transporter.sendMail({
        from: data.name + ' <' + data.email + '>',
        to: credentials.email,
        subject: 'Contact Form - blakenewman.co.uk',
        text: data.message
      }, function(error, info) {
        var code, message;
        if (error) {
          code = 200;
          message = 'Email stuck in cyberspace! oops!';
        } else {
          code = 400;
          message = 'It\'s alive! It\'s alive!';
        }
      });
    } else {
      code = 200;
      message = 'None shall pass';
    }
    res.status(code);
    res.send(message);
  });

  app.listen(9812);

}).call(this);
